import { createHash, sign, verify, randomUUID } from "node:crypto";
import type { EventEnvelope, EventStore, AppendCondition } from "./types.js";
import { IntegrityError, stableStringify } from "./core.js";
export interface IntegrityRecord{algorithm:"sha256";eventDigest:string;previousDigest?:string;}
export interface IntegrityEventEnvelope extends EventEnvelope{integrity:IntegrityRecord;}
export function eventPayloadForDigest(event:EventEnvelope):Record<string,unknown>{
  const metadata=event.metadata??{};
  const {__sif_event_digest:_eventDigest,__sif_previous_digest:_previousDigest,...applicationMetadata}=metadata;
  const {metadata:_metadata,...rest}=event;
  return Object.keys(applicationMetadata).length>0 ? {...rest,metadata:applicationMetadata} : rest as unknown as Record<string,unknown>;
}
export function eventDigest(event:EventEnvelope,previousDigest?:string):string{return createHash("sha256").update(stableStringify({event:eventPayloadForDigest(event),previousDigest})).digest("hex");}
export class HashChainEventStore implements EventStore{private readonly heads=new Map<string,string|undefined>();constructor(private readonly inner:EventStore){const streams=new Set(inner.all().map(e=>e.streamId));for(const streamId of streams){const events=inner.read(streamId).sort((a,b)=>a.streamVersion-b.streamVersion);let previous:string|undefined;let expectedVersion=1;for(const event of events){const md=event.metadata??{};const recorded=md.__sif_event_digest;if(!recorded)throw new IntegrityError(`Event ${event.eventId} is missing integrity digest metadata`);if(event.streamVersion!==expectedVersion)throw new IntegrityError(`Non-contiguous hash chain for stream ${streamId}`);if(event.streamVersion>1&&md.__sif_previous_digest!==previous)throw new IntegrityError(`Broken previous digest for event ${event.eventId}`);const calculated=eventDigest(event,previous);if(recorded!==calculated)throw new IntegrityError(`Event digest mismatch for event ${event.eventId}`);previous=calculated;expectedVersion+=1;}this.heads.set(streamId,previous);}}append<T extends Record<string,unknown>>(event:EventEnvelope<T>,condition:AppendCondition):void{const previousDigest=this.heads.get(event.streamId);const d=eventDigest(event,previousDigest);const enriched:EventEnvelope<T>={...structuredClone(event),metadata:{...(event.metadata??{}),__sif_event_digest:d,...(previousDigest?{__sif_previous_digest:previousDigest}:{})}};this.inner.append(enriched,condition);this.heads.set(event.streamId,d);}read(streamId:string,fromVersion=1):EventEnvelope[]{return this.inner.read(streamId,fromVersion);}all():EventEnvelope[]{return this.inner.all();}streamVersion(streamId:string):number{return this.inner.streamVersion(streamId);}verifyStream(streamId:string):boolean{const events=this.inner.read(streamId).sort((a,b)=>a.streamVersion-b.streamVersion);let previous:string|undefined;for(const event of events){const md=event.metadata??{};if(event.streamVersion<1)return false;if(event.streamVersion>1&&md.__sif_previous_digest!==previous)return false;const calculated=eventDigest(event,previous);if(md.__sif_event_digest!==calculated)return false;previous=calculated;}return true;}}
export interface SignedAttestation{attestationId:string;subjectDigest:string;subjectType:string;issuerId:string;algorithm:"ed25519";issuedAt:string;payload:Record<string,unknown>;signature:string;}
function canonicalAttestationPayload(a:Omit<SignedAttestation,"signature">):string{return stableStringify({attestationId:a.attestationId,subjectDigest:a.subjectDigest,subjectType:a.subjectType,issuerId:a.issuerId,algorithm:a.algorithm,issuedAt:a.issuedAt,payload:a.payload});}
export class AttestationSigner{constructor(private readonly issuerId:string,private readonly privateKeyPem:string){}issue(args:{subjectDigest:string;subjectType:string;payload?:Record<string,unknown>;issuedAt?:string}):SignedAttestation{const unsigned:Omit<SignedAttestation,"signature">={attestationId:randomUUID(),subjectDigest:args.subjectDigest,subjectType:args.subjectType,issuerId:this.issuerId,algorithm:"ed25519",issuedAt:args.issuedAt??new Date().toISOString(),payload:structuredClone(args.payload??{})};const signature=sign(null,new TextEncoder().encode(canonicalAttestationPayload(unsigned)),this.privateKeyPem).toString("base64url");return{...unsigned,signature};}}
export class AttestationVerifier{verify(attestation:SignedAttestation,publicKeyPem:string):boolean{const {signature:_signature,...unsigned}=attestation;return verify(null,new TextEncoder().encode(canonicalAttestationPayload(unsigned)),publicKeyPem,new Uint8Array(Buffer.from(attestation.signature,"base64url")));}}
