import { digest, stableStringify } from "./core.js";

export type SovereignProductId = "LARA_OS_REIE" | "QADRIX" | "SOVEREIGN_LIBRARY" | (string & {});
export type ProductPlane = "FEDERATION" | "POLICY" | "OBSERVABILITY" | "KNOWLEDGE" | "SYSTEMIC" | "CONTINUITY";
export type ProductOperationMode = "READ" | "CONTROLLED";
export type ProductEvaluationStatus = "PASS" | "FAIL" | "INDETERMINATE" | "UNAVAILABLE";
export interface SifProductCapability { capabilityId: string; plane: ProductPlane; version: string; mode: ProductOperationMode; authorityScopes: string[]; }
export interface SifProductDescriptor { productId: SovereignProductId; adapterVersion: string; protocolVersion: string; capabilities: SifProductCapability[]; allowedAuthorityScopes: string[]; allowedOperations: string[]; }
export interface SifProductAdapterLimits { maxAdapters: number; maxCapabilitiesPerAdapter: number; maxOperationsPerAdapter: number; maxRequestBytes: number; maxResponseBytes: number; maxEvidenceRefs: number; maxLedgerRecords: number; }
export interface SifProductRequest { requestId: string; productId: SovereignProductId; adapterVersion: string; operation: string; requestedCapabilities: string[]; authorityScopes: string[]; evidenceIds: string[]; payload: unknown; createdAt: string; }
export interface SifProductExecutionContext { request: SifProductRequest; descriptor: SifProductDescriptor; requestDigest: string; }
export interface SifProductResponse { requestId: string; productId: SovereignProductId; adapterVersion: string; operation: string; status: ProductEvaluationStatus; requestDigest: string; capabilityIds: string[]; authorityScopes: string[]; evidenceIds: string[]; output?: unknown; reason?: string; responseDigest: string; }
export interface SifProductAdapter { readonly descriptor: SifProductDescriptor; execute(request: SifProductRequest): Promise<SifProductResponse>; }
export type ProductOperationHandler = (context: SifProductExecutionContext) => Promise<unknown> | unknown;
export interface ProductEvidenceRecord { sequence: number; productId: SovereignProductId; requestDigest: string; responseDigest: string; recordedAt: string; previousDigest: string | null; recordDigest: string; }
export class SovereignProductError extends Error { constructor(readonly code: "INVALID_REQUEST" | "INVALID_DESCRIPTOR" | "RESOURCE_EXHAUSTED" | "CAPABILITY_DENIED" | "AUTHORITY_WIDENING" | "VERSION_MISMATCH" | "OPERATION_DENIED" | "PRODUCT_NOT_FOUND" | "EXECUTION_FAILED" | "REPLAY_MISMATCH" | "EVIDENCE_MISMATCH", message: string) { super(message); this.name = "SovereignProductError"; } }
const text=(n:string,v:string)=>{if(!v)throw new SovereignProductError("INVALID_REQUEST",`${n} must not be empty`)};
const positive=(n:string,v:number)=>{if(!Number.isSafeInteger(v)||v<=0)throw new SovereignProductError("RESOURCE_EXHAUSTED",`${n} must be positive`)};
const iso=(n:string,v:string)=>{if(!Number.isFinite(Date.parse(v)))throw new SovereignProductError("INVALID_REQUEST",`${n} must be a valid timestamp`)};
const unique=(v:string[],n:string)=>{if(new Set(v).size!==v.length)throw new SovereignProductError("INVALID_REQUEST",`${n} identifiers must be unique`)};
const subset=(r:string[],a:string[])=>{const s=new Set(a);return r.every(x=>s.has(x))};
const bytes=(v:unknown)=>new TextEncoder().encode(stableStringify(v)).byteLength;
const clone=<T>(v:T):T=>structuredClone(v);
function validateLimits(l:SifProductAdapterLimits){for(const[k,v]of Object.entries(l))positive(k,v as number)}
function validateDescriptor(d:SifProductDescriptor,l:SifProductAdapterLimits){text("productId",d.productId);text("adapterVersion",d.adapterVersion);text("protocolVersion",d.protocolVersion);if(d.capabilities.length>l.maxCapabilitiesPerAdapter)throw new SovereignProductError("RESOURCE_EXHAUSTED","Capability limit exceeded");if(d.allowedOperations.length>l.maxOperationsPerAdapter)throw new SovereignProductError("RESOURCE_EXHAUSTED","Operation limit exceeded");unique(d.capabilities.map(x=>x.capabilityId),"capability");unique(d.allowedAuthorityScopes,"authority");unique(d.allowedOperations,"operation");for(const c of d.capabilities){text("capabilityId",c.capabilityId);text("capability.version",c.version);unique(c.authorityScopes,`capability:${c.capabilityId}:authority`);if(!subset(c.authorityScopes,d.allowedAuthorityScopes))throw new SovereignProductError("INVALID_DESCRIPTOR",`Capability ${c.capabilityId} exceeds adapter authority`)}}
function normalizeRequest(r:SifProductRequest,l:SifProductAdapterLimits):SifProductRequest{validateLimits(l);text("requestId",r.requestId);text("productId",r.productId);text("adapterVersion",r.adapterVersion);text("operation",r.operation);iso("createdAt",r.createdAt);if(r.requestedCapabilities.length>l.maxCapabilitiesPerAdapter)throw new SovereignProductError("RESOURCE_EXHAUSTED","Requested capability limit exceeded");if(r.evidenceIds.length>l.maxEvidenceRefs)throw new SovereignProductError("RESOURCE_EXHAUSTED","Evidence reference limit exceeded");unique(r.requestedCapabilities,"requested capability");unique(r.authorityScopes,"authority");unique(r.evidenceIds,"evidence");if(bytes(r.payload)>l.maxRequestBytes)throw new SovereignProductError("RESOURCE_EXHAUSTED","Product request payload exceeds byte limit");return{...r,requestedCapabilities:[...r.requestedCapabilities].sort(),authorityScopes:[...r.authorityScopes].sort(),evidenceIds:[...r.evidenceIds].sort(),payload:clone(r.payload),createdAt:new Date(r.createdAt).toISOString()}}
export function computeProductRequestDigest(r:SifProductRequest,l:SifProductAdapterLimits){return digest(normalizeRequest(r,l))}
const responseDigest=(r:Omit<SifProductResponse,"responseDigest">)=>digest(r);
function failure(r:SifProductRequest,d:SifProductDescriptor,status:ProductEvaluationStatus,reason:string,rd=""):SifProductResponse{const b={requestId:r.requestId,productId:d.productId,adapterVersion:d.adapterVersion,operation:r.operation,status,requestDigest:rd,capabilityIds:[...r.requestedCapabilities].sort(),authorityScopes:[...r.authorityScopes].sort(),evidenceIds:[...r.evidenceIds].sort(),reason};return{...b,responseDigest:responseDigest(b)}}
class DefinedSifProductAdapter implements SifProductAdapter{
 private readonly descriptorValue:SifProductDescriptor;private readonly limits:SifProductAdapterLimits;private readonly handlers:ReadonlyMap<string,ProductOperationHandler>;
 constructor(d:SifProductDescriptor,h:ReadonlyMap<string,ProductOperationHandler>,l:SifProductAdapterLimits){validateDescriptor(d,l);this.descriptorValue=clone(d);this.handlers=new Map([...h.entries()].filter(([op])=>d.allowedOperations.includes(op)));this.limits={...l}}
 get descriptor(){return clone(this.descriptorValue)}
 async execute(request:SifProductRequest):Promise<SifProductResponse>{let r:SifProductRequest;try{r=normalizeRequest(request,this.limits)}catch(e){return failure(request,this.descriptorValue,e instanceof SovereignProductError&&e.code==="RESOURCE_EXHAUSTED"?"UNAVAILABLE":"FAIL",String(e))}const rd=digest(r),d=this.descriptorValue;if(r.productId!==d.productId)return failure(r,d,"UNAVAILABLE","Product adapter identity mismatch",rd);if(r.adapterVersion!==d.adapterVersion)return failure(r,d,"UNAVAILABLE","Adapter version mismatch",rd);if(!d.allowedOperations.includes(r.operation))return failure(r,d,"FAIL","Operation is not exposed by this adapter",rd);const cm=new Map(d.capabilities.map(c=>[c.capabilityId,c]));if(!subset(r.requestedCapabilities,[...cm.keys()]))return failure(r,d,"FAIL","Requested capability is not exposed by this adapter",rd);for(const id of r.requestedCapabilities){const c=cm.get(id);if(!c||!subset(c.authorityScopes,r.authorityScopes))return failure(r,d,"FAIL",`Authority required by capability ${id} is not present`,rd)}if(!subset(r.authorityScopes,d.allowedAuthorityScopes))return failure(r,d,"FAIL","Requested authority exceeds adapter authority",rd);const handler=this.handlers.get(r.operation);if(!handler)return failure(r,d,"UNAVAILABLE","No implementation handler is bound for operation",rd);let out:unknown;try{out=await handler({request:clone(r),descriptor:clone(d),requestDigest:rd})}catch(e){return failure(r,d,"INDETERMINATE",`Operation handler failed: ${String(e)}`,rd)}if(bytes(out)>this.limits.maxResponseBytes)return failure(r,d,"FAIL","Product response exceeds byte limit",rd);const b={requestId:r.requestId,productId:d.productId,adapterVersion:d.adapterVersion,operation:r.operation,status:"PASS" as const,requestDigest:rd,capabilityIds:[...r.requestedCapabilities],authorityScopes:[...r.authorityScopes],evidenceIds:[...r.evidenceIds],output:clone(out)};return{...b,responseDigest:responseDigest(b)}}}
function makeDescriptor(productId:SovereignProductId,capabilities:SifProductCapability[],scopes:string[],ops:string[]):SifProductDescriptor{return{productId,adapterVersion:"1.0.0",protocolVersion:"1.0",capabilities,allowedAuthorityScopes:scopes,allowedOperations:ops}}
function makeAdapter(id:SovereignProductId,c:SifProductCapability[],ops:string[],handlers:Record<string,ProductOperationHandler>,limits:SifProductAdapterLimits):SifProductAdapter{const scopes=[...new Set(c.flatMap(x=>x.authorityScopes))].sort();return new DefinedSifProductAdapter(makeDescriptor(id,c,scopes,ops),new Map(Object.entries(handlers)),limits)}
const DEFAULT_LIMITS:SifProductAdapterLimits={maxAdapters:16,maxCapabilitiesPerAdapter:32,maxOperationsPerAdapter:32,maxRequestBytes:64*1024,maxResponseBytes:128*1024,maxEvidenceRefs:32,maxLedgerRecords:1024};
export function defaultSifProductAdapterLimits(){return{...DEFAULT_LIMITS}}
const LARA_CAPABILITIES:SifProductCapability[]=[{capabilityId:"sif.policy.check",plane:"POLICY",version:"1",mode:"READ",authorityScopes:["product:lara:read"]},{capabilityId:"sif.knowledge.query",plane:"KNOWLEDGE",version:"1",mode:"READ",authorityScopes:["product:lara:read"]},{capabilityId:"sif.evaluation.run",plane:"OBSERVABILITY",version:"1",mode:"CONTROLLED",authorityScopes:["product:lara:execute"]},{capabilityId:"sif.systemic.query",plane:"SYSTEMIC",version:"1",mode:"READ",authorityScopes:["product:lara:read"]},{capabilityId:"sif.continuity.read",plane:"CONTINUITY",version:"1",mode:"READ",authorityScopes:["product:lara:read"]}];
const QADRIX_CAPABILITIES:SifProductCapability[]=[{capabilityId:"sif.policy.check",plane:"POLICY",version:"1",mode:"READ",authorityScopes:["product:qadrix:read"]},{capabilityId:"sif.knowledge.query",plane:"KNOWLEDGE",version:"1",mode:"READ",authorityScopes:["product:qadrix:read"]},{capabilityId:"sif.evaluation.run",plane:"OBSERVABILITY",version:"1",mode:"CONTROLLED",authorityScopes:["product:qadrix:execute"]},{capabilityId:"sif.continuity.read",plane:"CONTINUITY",version:"1",mode:"READ",authorityScopes:["product:qadrix:read"]}];
const LIBRARY_CAPABILITIES:SifProductCapability[]=[{capabilityId:"sif.knowledge.query",plane:"KNOWLEDGE",version:"1",mode:"READ",authorityScopes:["product:library:read"]},{capabilityId:"sif.evaluation.run",plane:"OBSERVABILITY",version:"1",mode:"CONTROLLED",authorityScopes:["product:library:execute"]},{capabilityId:"sif.continuity.read",plane:"CONTINUITY",version:"1",mode:"READ",authorityScopes:["product:library:read"]},{capabilityId:"sif.federation.inspect",plane:"FEDERATION",version:"1",mode:"READ",authorityScopes:["product:library:read"]}];
export function createLaraOsReieAdapter(h:Record<string,ProductOperationHandler>,l=DEFAULT_LIMITS){return makeAdapter("LARA_OS_REIE",LARA_CAPABILITIES,["policy.check","knowledge.query","evaluation.run","systemic.query","continuity.read"],h,l)}
export function createQadrixAdapter(h:Record<string,ProductOperationHandler>,l=DEFAULT_LIMITS){return makeAdapter("QADRIX",QADRIX_CAPABILITIES,["policy.check","knowledge.query","evaluation.run","continuity.read"],h,l)}
export function createSovereignLibraryAdapter(h:Record<string,ProductOperationHandler>,l=DEFAULT_LIMITS){return makeAdapter("SOVEREIGN_LIBRARY",LIBRARY_CAPABILITIES,["knowledge.query","evaluation.run","continuity.read","federation.inspect"],h,l)}
export class SifProductAdapterRegistry{private readonly adapters=new Map<string,SifProductAdapter>();constructor(private readonly limits:SifProductAdapterLimits=DEFAULT_LIMITS){validateLimits(limits)}register(a:SifProductAdapter){validateDescriptor(a.descriptor,this.limits);if(this.adapters.size>=this.limits.maxAdapters&&!this.adapters.has(a.descriptor.productId))throw new SovereignProductError("RESOURCE_EXHAUSTED","Product adapter limit exceeded");if(this.adapters.has(a.descriptor.productId))throw new SovereignProductError("INVALID_DESCRIPTOR","Product adapter already registered");this.adapters.set(a.descriptor.productId,a)}get(id:SovereignProductId){const a=this.adapters.get(id);if(!a)throw new SovereignProductError("PRODUCT_NOT_FOUND",`No adapter registered for ${id}`);return a}listDescriptors(){return[...this.adapters.values()].map(a=>clone(a.descriptor)).sort((a,b)=>a.productId.localeCompare(b.productId))}async dispatch(r:SifProductRequest){const a=this.adapters.get(r.productId);if(!a)return failure(r,{productId:r.productId,adapterVersion:r.adapterVersion,protocolVersion:"unknown",capabilities:[],allowedAuthorityScopes:[],allowedOperations:[]},"UNAVAILABLE","No product adapter is registered");return a.execute(r)}}
export class InMemoryProductEvidenceLedger{private readonly records:ProductEvidenceRecord[]=[];constructor(private readonly maxRecords=DEFAULT_LIMITS.maxLedgerRecords){positive("maxRecords",maxRecords)}append(r:SifProductResponse,recordedAt=new Date().toISOString()){if(this.records.length>=this.maxRecords)throw new SovereignProductError("RESOURCE_EXHAUSTED","Product evidence ledger limit exceeded");iso("recordedAt",recordedAt);const last=this.records[this.records.length-1],base={sequence:this.records.length+1,productId:r.productId,requestDigest:r.requestDigest,responseDigest:r.responseDigest,recordedAt:new Date(recordedAt).toISOString(),previousDigest:last?.recordDigest??null},record={...base,recordDigest:digest(base)};this.records.push(record);return clone(record)}list(){return clone(this.records)}verify(records=this.records){let previous:string|null=null;for(let i=0;i<records.length;i++){const record=records[i]!;if(record.sequence!==i+1||record.previousDigest!==previous)throw new SovereignProductError("EVIDENCE_MISMATCH","Product evidence chain linkage failed");const{recordDigest:_ignored,...base}=record;if(digest(base)!==record.recordDigest)throw new SovereignProductError("EVIDENCE_MISMATCH","Product evidence record digest mismatch");previous=record.recordDigest}}}
export function verifySifProductReplay(request:SifProductRequest,recorded:SifProductResponse,limits=DEFAULT_LIMITS){const rd=computeProductRequestDigest(request,limits);if(rd!==recorded.requestDigest)throw new SovereignProductError("REPLAY_MISMATCH","Product replay request digest mismatch");const{responseDigest:_ignored,...base}=recorded;if(responseDigest(base)!==recorded.responseDigest)throw new SovereignProductError("REPLAY_MISMATCH","Product replay response digest mismatch")}
