import test from "node:test";
import assert from "node:assert/strict";
import { BoundedFaultInjector, EpistemicKnowledgeStore, KnowledgeSemanticError, LegacyKnowledgeHandoff, ProvenanceGraph, SemanticCompatibilityEngine, SemanticReplayLog, VersionedOntologyRegistry, normalizeKnowledgeSemanticLimits, type EvidenceRef, type OntologyVersionInput } from "../src/index.js";

const LIMITS = normalizeKnowledgeSemanticLimits({ maxOntologyVersions: 4, maxConceptsPerOntology: 5, maxMappingsPerOntology: 6, maxKnowledgeRecords: 8, maxEvidencePerKnowledge: 2, maxProvenanceNodes: 8, maxTraversalDepth: 3, maxReplayOperations: 8, maxPayloadBytes: 8000, minCompatibilityConfidence: 0.8 });
const T = "2026-01-01T00:00:00.000Z"; const T2 = "2026-02-01T00:00:00.000Z";
const E: EvidenceRef = { evidenceId: "e1", sourceId: "source1", digest: "d1", capturedAt: T, scope: "local", confidence: 0.9 };
const baseOntology = (over: Partial<OntologyVersionInput> = {}): OntologyVersionInput => ({ ontologyId: "sif", version: "1.0", namespace: "sif:test", concepts: [{ conceptId: "active", label: "Active", definition: "accepted state" }, { conceptId: "closed", label: "Closed", definition: "closed state" }], createdAt: T, ...over });
function ex(fn: () => unknown, code: string): void { let got: unknown; try { fn(); } catch (e) { got = e; } assert.equal(got instanceof KnowledgeSemanticError ? got.code : undefined, code); }
async function axe(fn: () => Promise<unknown>, code: string): Promise<void> { let got: unknown; try { await fn(); } catch (e) { got = e; } assert.equal(got instanceof KnowledgeSemanticError ? got.code : undefined, code); }
function readyRegistry(): VersionedOntologyRegistry { const r = new VersionedOntologyRegistry(LIMITS); r.register(baseOntology()); return r; }
function knowledgeInput(over: Partial<Parameters<EpistemicKnowledgeStore["assert"]>[0]> = {}): Parameters<EpistemicKnowledgeStore["assert"]>[0] { return { subjectKey: "entity:1", predicate: "state", objectValue: "active", statement: "entity is active", status: "observed", scope: "local", validFrom: T, evidence: [E], provenanceId: "p1", ontologyId: "sif", ontologyVersion: "1.0", ...over }; }

// Ontology/versioning
 test("F6-001",()=>{const r=readyRegistry();assert.equal(r.get("sif","1.0")?.ontologyDigest.length,64);});
test("F6-002",()=>{const r=readyRegistry();assert.equal(r.digest("sif","1.0"),r.get("sif","1.0")!.ontologyDigest);});
test("F6-003",()=>{const r=readyRegistry();const x=r.get("sif","1.0")!;x.concepts[0]!.label="mutated";assert.equal(r.get("sif","1.0")!.concepts[0]!.label,"Active");});
test("F6-004",()=>{const r=new VersionedOntologyRegistry(LIMITS);assert.equal(r.register(baseOntology()).lifecycle,"DRAFT");});
test("F6-005",()=>{const r=readyRegistry();assert.equal(r.transition("sif","1.0","ACTIVE").lifecycle,"ACTIVE");});
test("F6-006",()=>{const r=readyRegistry();r.transition("sif","1.0","ACTIVE");assert.equal(r.transition("sif","1.0","RETIRED").lifecycle,"RETIRED");});
test("F6-007",()=>{const r=readyRegistry();r.transition("sif","1.0","ACTIVE");ex(()=>r.transition("sif","1.0","DRAFT"),"INVALID_LIFECYCLE");});
test("F6-008",()=>{const r=readyRegistry();const x=r.register(baseOntology());const y=r.register(baseOntology());assert.equal(x.ontologyDigest,y.ontologyDigest);});
test("F6-009",()=>{const r=readyRegistry();ex(()=>r.register(baseOntology({concepts:[...baseOntology().concepts,{conceptId:"active",label:"Dup",definition:"dup"}]})),"IMMUTABILITY_VIOLATION");});
test("F6-010",()=>{const r=readyRegistry();ex(()=>r.register(baseOntology({createdAt:"bad"})),"INVALID_INPUT");});
test("F6-011",()=>{const r=readyRegistry();ex(()=>r.register(baseOntology({concepts:Array.from({length:6},(_,i)=>({conceptId:String(i),label:String(i),definition:String(i)}))})),"RESOURCE_EXHAUSTED");});
test("F6-012",()=>{const r=readyRegistry();ex(()=>r.register(baseOntology({mappings:Array.from({length:7},(_,i)=>({mappingId:String(i),fromOntologyId:"sif",fromVersion:"1.0",fromConceptId:"active",toOntologyId:"sif",toVersion:"2.0",toConceptId:"active",relation:"equivalent",confidence:1,provenanceId:"p"}))})),"RESOURCE_EXHAUSTED");});
test("F6-013",()=>{const r=readyRegistry();const x=r.get("sif","1.0")!;assert.equal(r.hasConcept("sif","1.0",x.concepts[1]!.conceptId),true);});
test("F6-014",()=>{const r=new VersionedOntologyRegistry(LIMITS);ex(()=>r.register(baseOntology({concepts:[{conceptId:"x",label:"x",definition:"x"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"x",toOntologyId:"sif",toVersion:"2",toConceptId:"x",relation:"equivalent",confidence:2,provenanceId:"p"}]})),"INVALID_INPUT");});
test("F6-015",()=>{const r=readyRegistry();const before=r.digest("sif","1.0");r.transition("sif","1.0","ACTIVE");assert.notEqual(r.digest("sif","1.0"),before);});

// Compatibility
function compatRegistry(): VersionedOntologyRegistry { const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1.0",concepts:[{conceptId:"a",label:"A",definition:"A"}]}));r.register(baseOntology({version:"2.0",concepts:[{conceptId:"b",label:"B",definition:"B"}]}));return r; }
test("F6-016",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);assert.equal(e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"}).status,"EXACT");});
test("F6-017",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1.0",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1.0",fromConceptId:"a",toOntologyId:"sif",toVersion:"2.0",toConceptId:"b",relation:"equivalent",confidence:0.95,provenanceId:"p"}]}));r.register(baseOntology({version:"2.0",concepts:[{conceptId:"b",label:"B",definition:"B"}]}));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2.0",targetConceptId:"b"}).status,"COMPATIBLE");});
test("F6-018",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"broader",confidence:0.9,provenanceId:"p"}]}));r.register(baseOntology({version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}]}));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2",targetConceptId:"b"}).status,"COMPATIBLE");});
test("F6-019",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);ex(()=>e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"x",targetOntologyId:"sif",targetVersion:"2.0",targetConceptId:"b"}),"INVALID_INPUT");});
test("F6-020",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);assert.equal(e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2.0",targetConceptId:"b"}).status,"INCOMPATIBLE");});
test("F6-021",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m1",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"equivalent",confidence:0.9,provenanceId:"p"},{mappingId:"m2",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"equivalent",confidence:0.95,provenanceId:"p"}]}));r.register(baseOntology({version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}] }));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2",targetConceptId:"b"}).status,"INDETERMINATE");});
test("F6-022",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"equivalent",confidence:0.7,provenanceId:"p"}]}));r.register(baseOntology({version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}] }));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2",targetConceptId:"b"}).status,"INDETERMINATE");});
test("F6-023",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"approximate",confidence:0.95,provenanceId:"p"}]}));r.register(baseOntology({version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}] }));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2",targetConceptId:"b"}).status,"INDETERMINATE");});
test("F6-024",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"conditional",confidence:0.95,provenanceId:"p"}]}));r.register(baseOntology({version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}] }));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2",targetConceptId:"b"}).status,"INDETERMINATE");});
test("F6-025",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);assert.equal(e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"}).decisionDigest.length,64);});
test("F6-026",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);const a=e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"});const b=e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"});assert.equal(a.decisionDigest,b.decisionDigest);});
test("F6-027",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);assert.equal(e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"}).status,"EXACT");});
test("F6-028",()=>{const r=new VersionedOntologyRegistry(LIMITS);r.register(baseOntology({version:"1",concepts:[{conceptId:"a",label:"A",definition:"A"}],mappings:[{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"other",toVersion:"2",toConceptId:"b",relation:"equivalent",confidence:0.95,provenanceId:"p"}]}));r.register(baseOntology({ontologyId:"other",version:"2",concepts:[{conceptId:"b",label:"B",definition:"B"}] }));assert.equal(new SemanticCompatibilityEngine(r,LIMITS).resolve({sourceOntologyId:"sif",sourceVersion:"1",sourceConceptId:"a",targetOntologyId:"other",targetVersion:"2",targetConceptId:"b"}).status,"COMPATIBLE");});
test("F6-029",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);const x=e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"1.0",targetConceptId:"a"});assert.equal(x.sourceVersion,"1.0");});
test("F6-030",()=>{const r=compatRegistry();const e=new SemanticCompatibilityEngine(r,LIMITS);assert.equal(e.resolve({sourceOntologyId:"sif",sourceVersion:"1.0",sourceConceptId:"a",targetOntologyId:"sif",targetVersion:"2.0",targetConceptId:"b"}).status,"INCOMPATIBLE");});

// Epistemic knowledge
function store(): EpistemicKnowledgeStore { return new EpistemicKnowledgeStore(LIMITS); }
test("F6-031",()=>{const s=store();const k=s.assert(knowledgeInput());assert.equal(k.knowledgeId.length,64);});
test("F6-032",()=>{const s=store();const k=s.assert(knowledgeInput());const k2=s.assert(knowledgeInput());assert.deepEqual(k,k2);});
test("F6-033",()=>{const s=store();const k=s.assert(knowledgeInput());const x=s.get(k.knowledgeId)!;x.statement="tampered";assert.equal(s.get(k.knowledgeId)!.statement,"entity is active");});
test("F6-034",()=>{const s=store();ex(()=>s.assert(knowledgeInput({evidence:[]})),"INVALID_INPUT");});
test("F6-035",()=>{const s=store();const k=s.assert(knowledgeInput({status:"unknown",evidence:[]}));assert.equal(k.status,"unknown");});
test("F6-036",()=>{const s=store();ex(()=>s.assert(knowledgeInput({validUntil:T})),"INVALID_INPUT");});
test("F6-037",()=>{const s=store();const k=s.assert(knowledgeInput({validUntil:T2}));assert.equal(k.validUntil,T2);});
test("F6-038",()=>{const s=store();const a=s.assert(knowledgeInput({objectValue:"active"}));const b=s.assert(knowledgeInput({objectValue:"closed",statement:"entity is closed"}));assert.equal(s.queryAt("entity:1",T).contradictions.length,1);assert.deepEqual(s.queryAt("entity:1",T).contradictions[0]!.knowledgeIds.sort(),[a.knowledgeId,b.knowledgeId].sort());});
test("F6-039",()=>{const s=store();s.assert(knowledgeInput());assert.doesNotThrow(()=>s.assertNoContradiction("entity:missing",T));});
test("F6-040",()=>{const s=store();const old=s.assert(knowledgeInput({validUntil:T2}));const newer=s.assert(knowledgeInput({objectValue:"closed",statement:"closed",supersedesKnowledgeId:old.knowledgeId,validFrom:T2}));assert.equal(s.queryAt("entity:1",T).records.some(x=>x.knowledgeId===old.knowledgeId),true);assert.equal(s.queryAt("entity:1",T2).records.some(x=>x.knowledgeId===newer.knowledgeId),true);assert.equal(s.queryAt("entity:1",T2).records.some(x=>x.knowledgeId===old.knowledgeId),false);});
test("F6-041",()=>{const s=store();const old=s.assert(knowledgeInput());const r=s.assert(knowledgeInput({objectValue:"retracted",statement:"retract",retractsKnowledgeId:old.knowledgeId}));assert.equal(s.get(old.knowledgeId)?.knowledgeId,old.knowledgeId);assert.equal(r.retractsKnowledgeId,old.knowledgeId);});
test("F6-042",()=>{const s=store();const k=s.assert(knowledgeInput({sourceKind:"REMOTE_EVIDENCE"}));assert.equal(k.sourceKind,"REMOTE_EVIDENCE");assert.equal(k.sourceKind,"REMOTE_EVIDENCE");});

// Provenance graph
function graph(): ProvenanceGraph { return new ProvenanceGraph(LIMITS); }
test("F6-043",()=>{const g=graph();const n=g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:[],sourceIds:["s"]});assert.equal(n.nodeDigest.length,64);});
test("F6-044",()=>{const g=graph();g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:[],sourceIds:["s"]});const n=g.add({provenanceId:"p2",kind:"ASSERTION",label:"assert",recordedAt:T,parentIds:["p1"],sourceIds:["s"]});assert.equal(n.parentIds[0],"p1");});
test("F6-045",()=>{const g=graph();ex(()=>g.add({provenanceId:"p2",kind:"ASSERTION",label:"assert",recordedAt:T,parentIds:["missing"],sourceIds:[]}),"PROVENANCE_PARENT_MISSING");});
test("F6-046",()=>{const g=graph();g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:[],sourceIds:[]});ex(()=>g.add({provenanceId:"p1",kind:"SOURCE",label:"changed",recordedAt:T,parentIds:[],sourceIds:[]}),"IMMUTABILITY_VIOLATION");});
test("F6-047",()=>{const g=graph();ex(()=>g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:["p1"],sourceIds:[]}),"PROVENANCE_CYCLE");});
test("F6-048",()=>{const g=graph();for(let i=1;i<=4;i++)g.add({provenanceId:`p${i}`,kind:"ASSERTION",label:`p${i}`,recordedAt:T,parentIds:i===1?[]:[`p${i-1}`],sourceIds:[]});assert.equal(g.ancestors("p4").length,3);});
test("F6-049",()=>{const g=graph();g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:[],sourceIds:[]});ex(()=>g.ancestors("p1",4),"RESOURCE_EXHAUSTED");});
test("F6-050",()=>{const g=graph();g.add({provenanceId:"p1",kind:"SOURCE",label:"source",recordedAt:T,parentIds:[],sourceIds:[]});const d1=g.graphDigest();const d2=g.graphDigest();assert.equal(d1,d2);});

// Replay
function replay(): SemanticReplayLog { return new SemanticReplayLog(LIMITS); }
test("F6-051",()=>{const r=replay();const op=r.append({kind:"CONCEPT",ontologyId:"sif",ontologyVersion:"1",payload:{conceptId:"a",label:"A",definition:"A"},occurredAt:T});assert.equal(op.operationId.length,64);});
test("F6-052",()=>{const r=replay();r.append({kind:"CONCEPT",ontologyId:"sif",ontologyVersion:"1",payload:{conceptId:"a",label:"A",definition:"A"},occurredAt:T});const s=r.replay("sif","1");assert.equal(s.concepts[0]!.conceptId,"a");});
test("F6-053",()=>{const a=replay();a.append({kind:"CONCEPT",ontologyId:"sif",ontologyVersion:"1",payload:{conceptId:"a",label:"A",definition:"A"},occurredAt:T});const b=a.replay("sif","1");assert.equal(b.snapshotDigest.length,64);});
test("F6-054",()=>{const r=replay();r.append({kind:"CONCEPT",ontologyId:"sif",ontologyVersion:"1",payload:{conceptId:"a",label:"A",definition:"A"},occurredAt:T});ex(()=>r.replay("sif","1","wrong"),"REPLAY_MISMATCH");});
test("F6-055",()=>{const r=replay();r.append({kind:"MAPPING",ontologyId:"sif",ontologyVersion:"1",payload:{mappingId:"m",fromOntologyId:"sif",fromVersion:"1",fromConceptId:"a",toOntologyId:"sif",toVersion:"2",toConceptId:"b",relation:"equivalent",confidence:1,provenanceId:"p"},occurredAt:T});assert.equal(r.replay("other","1").operationCount,0);});
test("F6-056",()=>{const r=new SemanticReplayLog(LIMITS);axe(r.append({kind:"CONCEPT",ontologyId:"sif",ontologyVersion:"1",payload:"x".repeat(9000),occurredAt:T}) as unknown as () => Promise<unknown>,"RESOURCE_EXHAUSTED");});

// Legacy handoff + cross-phase safety
function legacy(): LegacyKnowledgeHandoff { return new LegacyKnowledgeHandoff(store()); }
test("F6-057",()=>{const h=legacy();const out=h.adopt({legacyId:"old1",statement:"legacy fact",status:"observed",scope:"legacy",capturedAt:T,evidence:[E],provenanceId:"p",ontologyId:"sif",ontologyVersion:"1"});assert.equal(out.legacyId,"old1");assert.equal(out.sourceKind,"LEGACY");});
test("F6-058",()=>{const h=legacy();const out=h.adopt({legacyId:"old2",statement:"legacy fact",status:"observed",scope:"legacy",capturedAt:T,evidence:[E],provenanceId:"p",ontologyId:"sif",ontologyVersion:"1"});assert.equal(out.ontologyVersion,"1");});
test("F6-059",()=>{const h=legacy();assert.throws(()=>h.assertNoAuthorityWidening(),KnowledgeSemanticError);});
test("F6-060",()=>{const s=store();const h=new LegacyKnowledgeHandoff(s);const out=h.adopt({legacyId:"old3",statement:"remote",status:"observed",scope:"remote",capturedAt:T,evidence:[E],provenanceId:"p",ontologyId:"sif",ontologyVersion:"1"});const k=s.get(out.knowledgeId)!;assert.equal(k.sourceKind,"LEGACY");assert.equal(k.scope,"remote");assert.equal(k.knowledgeId.length,64);});
