import test from "node:test";
import assert from "node:assert/strict";
import {
  InMemoryPolicyDecisionLedger,
  LocalDeterministicPolicyAdapter,
  PolicyGovernance,
  PolicyGovernanceError,
  PolicyRegistry,
  computePolicyDigest,
  normalizePolicyRequest,
  type PolicyBundle,
  type PolicyDecisionAdapter,
  type PolicyGovernanceErrorCode,
} from "../src/index.js";

const T0="2026-09-16T00:00:00.000Z"; const T1="2026-09-17T00:00:00.000Z"; const T2="2026-09-18T00:00:00.000Z";
function bundle(o:Partial<PolicyBundle>={ }):PolicyBundle{const b:Omit<PolicyBundle,"digest">={policyId:"access",version:"1",source:"local",provenanceId:"prov-1",effectiveFrom:T0,expiresAt:T2,rules:[{id:"allow",effect:"ALLOW",capabilityId:"evidence.read",scopePrefix:"evidence",reason:"allow"},{id:"deny",effect:"DENY",capabilityId:"evidence.read",scopePrefix:"evidence/secret",reason:"deny"}],lifecycle:"registered",...o};const{lifecycle:_l,...c}=b;return{...b,digest:computePolicyDigest(c)};}
function req(o:Partial<{subjectId:string;capabilityId:string;scope:string;at:string;context:Record<string,unknown>}>={}){return{subjectId:"s1",capabilityId:"evidence.read",scope:"evidence/case",at:T1,...o};}
function lim(o:Partial<ConstructorParameters<typeof PolicyGovernance>[2]>={}){return{maxPolicyBytes:100000,maxRules:100,maxContextEntries:20,maxContextBytes:10000,maxVersionsPerPolicy:10,maxConcurrentEvaluations:2,...o};}
function ready(r:PolicyRegistry,b=bundle()){r.register(b);return r.activate(b.policyId,b.version,T1);}
async function code(p:Promise<unknown>,c:PolicyGovernanceErrorCode){let got=false;try{await p;}catch(e){got=e instanceof PolicyGovernanceError&&e.code===c;}assert.equal(got,true);}

// F4-001..010
 test("F4-001 digest",()=>{const b=bundle();const{digest:_d,lifecycle:_l,...c}=b;assert.equal(b.digest,computePolicyDigest(c));});
 test("F4-002 identical duplicate",()=>{const r=new PolicyRegistry();const b=bundle();r.register(b);r.register(b);assert.equal(r.list("access").length,1);});
 test("F4-003 divergent duplicate",()=>{const r=new PolicyRegistry();r.register(bundle());assert.throws(()=>r.register(bundle({rules:[{id:"x",effect:"ALLOW",reason:"x"}]})),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INTEGRITY_FAILURE");});
 test("F4-004 malformed bundle",()=>{const r=new PolicyRegistry();assert.throws(()=>r.register(bundle({rules:[]})),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INVALID");});
 test("F4-005 activation",()=>{const r=new PolicyRegistry();r.register(bundle());assert.equal(r.get("access","1").lifecycle,"registered");assert.equal(r.activate("access","1",T1).lifecycle,"active");});
 test("F4-006 retirement",()=>{const r=new PolicyRegistry();ready(r);r.retire("access","1",T2);assert.throws(()=>r.resolve("access",T2),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_RETIRED");});
 test("F4-007 overlap rejected",()=>{const r=new PolicyRegistry();r.register(bundle({version:"1"}));r.register(bundle({version:"2"}));r.activate("access","1",T1);assert.throws(()=>r.activate("access","2",T1),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_AMBIGUOUS");});
 test("F4-008 historical resolution",()=>{const r=new PolicyRegistry();r.register(bundle({version:"1",expiresAt:T1}));r.register(bundle({version:"2",effectiveFrom:T1,rules:[{id:"new",effect:"ALLOW",reason:"new"}]}));r.activate("access","1",T0);r.retire("access","1",T1);r.activate("access","2",T1);assert.equal(r.resolve("access",T0,"1").version,"1");assert.equal(r.resolve("access",T1).version,"2");});
 test("F4-009 expiry",()=>{const r=new PolicyRegistry();r.register(bundle({expiresAt:T1}));assert.throws(()=>r.activate("access","1",T1),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_EXPIRED");});
 test("F4-010 request validation",()=>{assert.throws(()=>normalizePolicyRequest(req({subjectId:""})),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INVALID");});

// F4-011..023
 test("F4-011 allow",async()=>{const r=new PolicyRegistry();const b=ready(r);const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"ALLOW");});
 test("F4-012 deny",async()=>{const r=new PolicyRegistry();const b=ready(r);const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluate(req({scope:"evidence/secret/x"}),b.policyId);assert.equal(d.effect,"DENY");});
 test("F4-013 default deny",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"other",effect:"ALLOW",capabilityId:"other",reason:"other"}]}));const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"DENY");});
 test("F4-014 deny overrides",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"a",effect:"ALLOW",capabilityId:"evidence.read",scopePrefix:"evidence",reason:"a"},{id:"d",effect:"DENY",capabilityId:"evidence.read",scopePrefix:"evidence",reason:"d"}]}));assert.equal((await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluate(req(),b.policyId)).effect,"DENY");});
 test("F4-015 provider allow",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"ALLOW",provider:"opa",providerVersion:"1",decisionId:"pd",ruleId:"pr",reason:"ok",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"ALLOW");assert.equal(d.evidence.providerDecisionId,"pd");});
 test("F4-016 provider deny",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"DENY",provider:"cedar",providerVersion:"1",decisionId:"pd",ruleId:"pr",reason:"no",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"DENY");});
 test("F4-017 provider unavailable",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"PROVIDER_UNAVAILABLE",provider:"opa",providerVersion:"1",reason:"down",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"INDETERMINATE");});
 test("F4-018 malformed provider",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"ALLOW",provider:"",providerVersion:"1",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};await code(new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId),"POLICY_INVALID");});
 test("F4-019 provider incompatible",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"PROVIDER_INCOMPATIBLE",provider:"x",providerVersion:"0",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.evidence.failureCode,"POLICY_PROVIDER_INCOMPATIBLE");});
 test("F4-020 evidence attribution",async()=>{const r=new PolicyRegistry();const b=ready(r);const l=new InMemoryPolicyDecisionLedger();const g=new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim(),l);const d=await g.evaluate(req(),b.policyId);assert.equal(l.all()[0]!.evidence.policyDigest,b.digest);assert.equal(d.evidence.requestDigest,normalizePolicyRequest(req()).requestDigest);});
 test("F4-021 context identity",async()=>{const r=new PolicyRegistry();const b=ready(r);const g=new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim());const a=await g.evaluate(req({context:{region:"eg"}}),b.policyId);const d=await g.evaluate(req({context:{region:"us"}}),b.policyId);assert.notEqual(a.evidence.requestDigest,d.evidence.requestDigest);});
 test("F4-022 remote request still local",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"other",effect:"ALLOW",capabilityId:"other",reason:"other"}]}));const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluateFederated(req(),b.policyId,{originDomain:"remote",requestedCapability:"evidence.read"});assert.equal(d.effect,"DENY");});
 test("F4-023 remote assertion cannot widen",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"n",effect:"ALLOW",capabilityId:"evidence.read",scopePrefix:"evidence/narrow",reason:"n"}]}));const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluateFederated(req({scope:"evidence/broad"}),b.policyId,{originDomain:"trusted",remotePolicyAssertion:"ALLOW"});assert.equal(d.effect,"DENY");});

// F4-024..040
 test("F4-024 policy size",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"a",effect:"ALLOW",reason:"x".repeat(5000)}]}));let calls=0;const a:PolicyDecisionAdapter={evaluate:async()=>{calls++;return{outcome:"ALLOW",provider:"x",providerVersion:"1",decisionId:"1",ruleId:"a",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest};}};await code(new PolicyGovernance(r,a,lim({maxPolicyBytes:100})).evaluate(req(),b.policyId),"POLICY_RESOURCE_EXHAUSTED");assert.equal(calls,0);});
 test("F4-025 rule limit",async()=>{const r=new PolicyRegistry();const rules=Array.from({length:4},(_,i)=>({id:`r${i}`,effect:"ALLOW" as const,reason:"r"}));const b=ready(r,bundle({rules}));await code(new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim({maxRules:2})).evaluate(req(),b.policyId),"POLICY_RESOURCE_EXHAUSTED");});
 test("F4-026 context limit",async()=>{const r=new PolicyRegistry();const b=ready(r);await code(new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim({maxContextEntries:1})).evaluate(req({context:{a:1,b:2}}),b.policyId),"POLICY_RESOURCE_EXHAUSTED");});
 test("F4-027 concurrency",async()=>{const r=new PolicyRegistry();const b=ready(r);let release!:()=>void;const hold=new Promise<void>(x=>{release=x;});let calls=0;const a:PolicyDecisionAdapter={evaluate:async()=>{calls++;await hold;return{outcome:"ALLOW",provider:"x",providerVersion:"1",decisionId:"1",ruleId:"a",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest};}};const g=new PolicyGovernance(r,a,lim({maxConcurrentEvaluations:1}));const first=g.evaluate(req(),b.policyId);await new Promise(r=>setTimeout(r,0));await code(g.evaluate(req({subjectId:"s2"}),b.policyId),"POLICY_RESOURCE_EXHAUSTED");release();await first;assert.equal(calls,1);});
 test("F4-028 deterministic replay",async()=>{const r=new PolicyRegistry();const b=ready(r);const g=new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim());assert.deepEqual(await g.evaluate(req(),b.policyId),await g.evaluate(req(),b.policyId));});
 test("F4-029 digest tamper",()=>{const r=new PolicyRegistry();assert.throws(()=>r.register({...bundle(),digest:"0".repeat(64)}),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INTEGRITY_FAILURE");});
 test("F4-030 provenance tamper",()=>{const r=new PolicyRegistry();const b=bundle();r.register(b);assert.throws(()=>r.register({...b,provenanceId:"attacker"}),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INTEGRITY_FAILURE");});
 test("F4-031 provider cannot widen",async()=>{const r=new PolicyRegistry();const b=ready(r,bundle({rules:[{id:"n",effect:"ALLOW",capabilityId:"evidence.read",scopePrefix:"evidence/narrow",reason:"n"}]}));let calls=0;const a:PolicyDecisionAdapter={evaluate:async()=>{calls++;return{outcome:"ALLOW",provider:"remote",providerVersion:"1",decisionId:"1",ruleId:"remote",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest};}};assert.equal((await new PolicyGovernance(r,a,lim()).evaluate(req({scope:"evidence/broad"}),b.policyId)).effect,"DENY");assert.equal(calls,0);});
 test("F4-032 missing policy",async()=>{await code(new PolicyGovernance(new PolicyRegistry(),new LocalDeterministicPolicyAdapter(),lim()).evaluate(req(),"missing"),"POLICY_NOT_FOUND");});
 test("F4-033 ambiguous",()=>{const r=new PolicyRegistry();r.register(bundle({version:"1"}));r.register(bundle({version:"2"}));r.activate("access","1",T1);assert.throws(()=>r.activate("access","2",T1),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_AMBIGUOUS");});
 test("F4-034 incompatibility attribution",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"PROVIDER_INCOMPATIBLE",provider:"x",providerVersion:"0",reason:"no",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.evidence.failureCode,"POLICY_PROVIDER_INCOMPATIBLE");});
 test("F4-035 invalid result never allows",async()=>{const r=new PolicyRegistry();const b=ready(r);const a:PolicyDecisionAdapter={evaluate:async()=>({outcome:"INVALID_RESULT",provider:"x",providerVersion:"1",reason:"bad",policyId:b.policyId,policyVersion:b.version,policyDigest:b.digest})};const d=await new PolicyGovernance(r,a,lim()).evaluate(req(),b.policyId);assert.equal(d.effect,"INDETERMINATE");});
 test("F4-036 duplicate content never replaces",()=>{const r=new PolicyRegistry();const b=bundle();r.register(b);assert.throws(()=>r.register(bundle({rules:[{id:"other",effect:"ALLOW",reason:"other"}]})),e=>e instanceof PolicyGovernanceError&&e.code==="POLICY_INTEGRITY_FAILURE");});
 test("F4-037 repeated activation idempotent",()=>{const r=new PolicyRegistry();r.register(bundle());r.activate("access","1",T1);r.activate("access","1",T1);assert.equal(r.lifecycleLog().filter(x=>x.action==="ACTIVATE").length,1);});
 test("F4-038 history bound after retirement",async()=>{const r=new PolicyRegistry();const b=ready(r);const g=new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim());const a=await g.evaluate(req(),b.policyId);r.retire(b.policyId,b.version,T2);const d=await g.evaluate(req({at:T1}),b.policyId,b.version);assert.deepEqual(a,d);});
 test("F4-039 ledger caller immutable",async()=>{const r=new PolicyRegistry();const b=ready(r);const l=new InMemoryPolicyDecisionLedger();const g=new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim(),l);const d=await g.evaluate(req(),b.policyId);const c=l.all()[0]!;c.evidence.reason="changed";assert.equal(l.all()[0]!.evidence.reason,d.evidence.reason);});
 test("F4-040 federation local outcome",async()=>{const r=new PolicyRegistry();const b=ready(r);const d=await new PolicyGovernance(r,new LocalDeterministicPolicyAdapter(),lim()).evaluateFederated(req(),b.policyId,{originDomain:"remote",peerId:"p",requestedCapability:"evidence.read",negotiatedCapability:"evidence.read",remotePolicyAssertion:"ALLOW"});assert.equal(d.effect,"ALLOW");assert.equal(d.evidence.policyVersion,b.version);});
