import test from "node:test";
import assert from "node:assert/strict";
import {
  InMemoryPolicyDecisionLedger,
  LocalDeterministicPolicyAdapter,
  PolicyGovernance,
  PolicyGovernanceError,
  PolicyRegistry,
  computePolicyDigest,
  normalizePolicyRequest,
  type ExternalPolicyResult,
  type PolicyBundle,
  type PolicyDecisionAdapter,
  type PolicyGovernanceErrorCode,
} from "../src/index.js";

const t0 = "2026-09-16T00:00:00.000Z";
const t1 = "2026-09-17T00:00:00.000Z";
const t2 = "2026-09-18T00:00:00.000Z";

function bundle(overrides: Partial<PolicyBundle> = {}): PolicyBundle {
  const base: Omit<PolicyBundle, "digest"> = {
    policyId: "access", version: "1", source: "local", provenanceId: "prov-1", effectiveFrom: t0, expiresAt: t2,
    rules: [
      { id: "allow-evidence", effect: "ALLOW", capabilityId: "evidence.read", scopePrefix: "evidence", reason: "Evidence allowed" },
      { id: "deny-secret", effect: "DENY", capabilityId: "evidence.read", scopePrefix: "evidence/secret", reason: "Secret denied" },
    ], lifecycle: "registered", ...overrides,
  };
  const { lifecycle: _lifecycle, ...content } = base;
  return { ...base, digest: computePolicyDigest(content) };
}

function req(overrides: Partial<PolicyBundle> & Partial<{ subjectId: string; capabilityId: string; scope: string; at: string; context: Record<string, unknown> }> = {}) {
  return { subjectId: "subject-1", capabilityId: "evidence.read", scope: "evidence/case-1", at: t1, ...overrides };
}
function lim(overrides: Partial<ConstructorParameters<typeof PolicyGovernance>[2]> = {}) {
  return { maxPolicyBytes: 100_000, maxRules: 100, maxContextEntries: 20, maxContextBytes: 10_000, maxVersionsPerPolicy: 10, maxConcurrentEvaluations: 2, ...overrides };
}
function ready(registry: PolicyRegistry, item = bundle()): PolicyBundle { registry.register(item); return registry.activate(item.policyId, item.version, t1); }
async function expectCode(work: () => Promise<unknown>, code: PolicyGovernanceErrorCode): Promise<void> {
  try { await work(); assert.fail(`expected ${code}`); } catch (error) { assert.ok(error instanceof PolicyGovernanceError); assert.equal(error.code, code); }
}

// F4-001..F4-010: identity, lifecycle and resolution.
test("F4-001 deterministic policy digest", () => { const item = bundle(); assert.equal(item.digest, computePolicyDigest({ policyId: item.policyId, version: item.version, source: item.source, provenanceId: item.provenanceId, effectiveFrom: item.effectiveFrom, expiresAt: item.expiresAt, rules: item.rules })); });
test("F4-002 identical duplicate registration is idempotent", () => { const r = new PolicyRegistry(); const x = bundle(); r.register(x); r.register(x); assert.equal(r.list("access").length, 1); });
test("F4-003 divergent duplicate registration fails integrity", () => { const r = new PolicyRegistry(); r.register(bundle()); assert.throws(() => r.register(bundle({ rules: [{ id: "different", effect: "ALLOW", reason: "different" }] })), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INTEGRITY_FAILURE"); assert.equal(r.get("access", "1").rules[0]?.id, "allow-evidence"); });
test("F4-004 malformed policy fails closed", () => { const r = new PolicyRegistry(); assert.throws(() => r.register(bundle({ rules: [] })), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INVALID"); });
test("F4-005 activation is explicit", () => { const r = new PolicyRegistry(); r.register(bundle()); assert.equal(r.get("access", "1").lifecycle, "registered"); assert.equal(r.activate("access", "1", t1).lifecycle, "active"); });
test("F4-006 current resolution excludes retired version", () => { const r = new PolicyRegistry(); ready(r); r.retire("access", "1", t2); assert.throws(() => r.resolve("access", t2), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_RETIRED"); });
test("F4-007 overlapping active versions fail closed", () => { const r = new PolicyRegistry(); r.register(bundle({ version: "1" })); r.register(bundle({ version: "2" })); r.activate("access", "1", t1); assert.throws(() => r.activate("access", "2", t1), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_AMBIGUOUS"); });
test("F4-008 historical timestamp resolution is deterministic", () => { const r = new PolicyRegistry(); r.register(bundle({ version: "1", expiresAt: t1 })); r.register(bundle({ version: "2", effectiveFrom: t1, rules: [{ id: "allow-new", effect: "ALLOW", reason: "new" }] })); r.activate("access", "1", t0); r.retire("access", "1", t1); r.activate("access", "2", t1); assert.equal(r.resolve("access", t0, "1").version, "1"); assert.equal(r.resolve("access", t1).version, "2"); });
test("F4-009 expired version rejects activation", () => { const r = new PolicyRegistry(); r.register(bundle({ expiresAt: t1 })); assert.throws(() => r.activate("access", "1", t1), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_EXPIRED"); });
test("F4-010 invalid request identity fails closed", () => { assert.throws(() => normalizePolicyRequest(req({ subjectId: "" })), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INVALID"); assert.throws(() => normalizePolicyRequest(req({ capabilityId: "" })), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INVALID"); assert.throws(() => normalizePolicyRequest(req({ scope: "" })), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INVALID"); });

// F4-011..F4-023: decisions, adapters and sovereignty.
test("F4-011 explicit allow", async () => { const r = new PolicyRegistry(); const x = ready(r); const d = await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "ALLOW"); assert.equal(d.evidence.ruleId, "allow-evidence"); });
test("F4-012 explicit deny", async () => { const r = new PolicyRegistry(); const x = ready(r); const d = await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluate(req({ scope: "evidence/secret/case" }), x.policyId); assert.equal(d.effect, "DENY"); assert.equal(d.evidence.ruleId, "deny-secret"); });
test("F4-013 default deny", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "other", effect: "ALLOW", capabilityId: "other", reason: "other" }] })); const d = await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "DENY"); assert.equal(d.evidence.ruleId, "default-deny"); });
test("F4-014 deny overrides allow", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "allow", effect: "ALLOW", capabilityId: "evidence.read", scopePrefix: "evidence", reason: "allow" }, { id: "deny", effect: "DENY", capabilityId: "evidence.read", scopePrefix: "evidence", reason: "deny" }] })); assert.equal((await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluate(req(), x.policyId)).effect, "DENY"); });
test("F4-015 provider allow is locally attributable", async () => { const r = new PolicyRegistry(); const x = ready(r); const adapter: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "ALLOW", provider: "opa-shaped", providerVersion: "1", decisionId: "d1", ruleId: "p1", reason: "ok", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, adapter, lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "ALLOW"); assert.equal(d.evidence.providerDecisionId, "d1"); });
test("F4-016 provider deny is retained", async () => { const r = new PolicyRegistry(); const x = ready(r); const adapter: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "DENY", provider: "cedar-shaped", providerVersion: "1", decisionId: "d2", ruleId: "p2", reason: "no", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, adapter, lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "DENY"); assert.equal(d.evidence.providerDecisionId, "d2"); });
test("F4-017 provider unavailable never allows", async () => { const r = new PolicyRegistry(); const x = ready(r); const adapter: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "PROVIDER_UNAVAILABLE", provider: "opa", providerVersion: "1", reason: "down", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, adapter, lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "INDETERMINATE"); assert.equal(d.evidence.failureCode, "POLICY_PROVIDER_UNAVAILABLE"); });
test("F4-018 malformed provider result fails closed", async () => { const r = new PolicyRegistry(); const x = ready(r); const adapter: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "ALLOW", provider: "", providerVersion: "1", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; await expectCode(() => new PolicyGovernance(r, adapter, lim()).evaluate(req(), x.policyId), "POLICY_INVALID"); });
test("F4-019 provider incompatibility is typed", async () => { const r = new PolicyRegistry(); const x = ready(r); const adapter: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "PROVIDER_INCOMPATIBLE", provider: "provider", providerVersion: "0", reason: "unsupported", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, adapter, lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "INDETERMINATE"); assert.equal(d.evidence.failureCode, "POLICY_PROVIDER_INCOMPATIBLE"); });
test("F4-020 evidence contains exact policy and request identities", async () => { const r = new PolicyRegistry(); const x = ready(r); const ledger = new InMemoryPolicyDecisionLedger(); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim(), ledger); const d = await g.evaluate(req(), x.policyId); assert.equal(d.evidence.policyDigest, x.digest); assert.equal(d.evidence.requestDigest, normalizePolicyRequest(req()).requestDigest); assert.deepEqual(ledger.all()[0], d); });
test("F4-021 context changes request and decision identity", async () => { const r = new PolicyRegistry(); const x = ready(r); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()); const a = await g.evaluate(req({ context: { region: "eg" } }), x.policyId); const b = await g.evaluate(req({ context: { region: "us" } }), x.policyId); assert.notEqual(a.evidence.requestDigest, b.evidence.requestDigest); assert.notEqual(a.evidence.decisionId, b.evidence.decisionId); });
test("F4-022 remote requested capability does not bypass local policy", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "other", effect: "ALLOW", capabilityId: "other", reason: "other" }] })); const d = await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluateFederated(req(), x.policyId, { originDomain: "remote", requestedCapability: "evidence.read", negotiatedCapability: "evidence.read" }); assert.equal(d.effect, "DENY"); });
test("F4-023 trusted remote assertion cannot widen local policy", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "narrow", effect: "ALLOW", capabilityId: "evidence.read", scopePrefix: "evidence/narrow", reason: "narrow" }] })); const d = await new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()).evaluateFederated(req({ scope: "evidence/broad" }), x.policyId, { originDomain: "trusted", remotePolicyAssertion: "ALLOW" }); assert.equal(d.effect, "DENY"); });

// F4-024..F4-040: limits, determinism, failures, concurrency and evidence immutability.
test("F4-024 oversized policy rejected before adapter", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "allow", effect: "ALLOW", reason: "x".repeat(5000) }] })); let calls = 0; const a: PolicyDecisionAdapter = { evaluate: async () => { calls += 1; return { outcome: "ALLOW", provider: "x", providerVersion: "1", decisionId: "1", ruleId: "r", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }; } }; await expectCode(() => new PolicyGovernance(r, a, lim({ maxPolicyBytes: 100 })).evaluate(req(), x.policyId), "POLICY_RESOURCE_EXHAUSTED"); assert.equal(calls, 0); });
test("F4-025 excessive rules rejected", async () => { const r = new PolicyRegistry(); const rules = Array.from({ length: 4 }, (_, i) => ({ id: `r${i}`, effect: "ALLOW" as const, reason: "r" })); const x = ready(r, bundle({ rules })); let calls = 0; const a: PolicyDecisionAdapter = { evaluate: async () => { calls += 1; return { outcome: "ALLOW", provider: "x", providerVersion: "1", decisionId: "1", ruleId: "r", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }; } }; await expectCode(() => new PolicyGovernance(r, a, lim({ maxRules: 2 })).evaluate(req(), x.policyId), "POLICY_RESOURCE_EXHAUSTED"); assert.equal(calls, 0); });
test("F4-026 excessive context rejected", async () => { const r = new PolicyRegistry(); const x = ready(r); let calls = 0; const a: PolicyDecisionAdapter = { evaluate: async () => { calls += 1; return { outcome: "ALLOW", provider: "x", providerVersion: "1", decisionId: "1", ruleId: "r", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }; } }; await expectCode(() => new PolicyGovernance(r, a, lim({ maxContextEntries: 1 })).evaluate(req({ context: { a: 1, b: 2 } }), x.policyId), "POLICY_RESOURCE_EXHAUSTED"); assert.equal(calls, 0); });
test("F4-027 concurrent evaluation limit blocks bypass", async () => { const r = new PolicyRegistry(); const x = ready(r); let release!: () => void; const hold = new Promise<void>((resolve) => { release = resolve; }); let calls = 0; const a: PolicyDecisionAdapter = { evaluate: async () => { calls += 1; await hold; return { outcome: "ALLOW", provider: "x", providerVersion: "1", decisionId: "1", ruleId: "r", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }; } }; const g = new PolicyGovernance(r, a, lim({ maxConcurrentEvaluations: 1 })); const first = g.evaluate(req(), x.policyId); await new Promise((resolve) => setTimeout(resolve, 0)); await expectCode(() => g.evaluate(req({ subjectId: "other" }), x.policyId), "POLICY_RESOURCE_EXHAUSTED"); release(); await first; assert.equal(calls, 1); });
test("F4-028 identical replay produces identical evidence", async () => { const r = new PolicyRegistry(); const x = ready(r); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()); assert.deepEqual(await g.evaluate(req(), x.policyId), await g.evaluate(req(), x.policyId)); });
test("F4-029 digest tamper fails integrity", () => { const r = new PolicyRegistry(); assert.throws(() => r.register({ ...bundle(), digest: "0".repeat(64) }), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INTEGRITY_FAILURE"); });
test("F4-030 provenance change without digest change fails integrity", () => { const r = new PolicyRegistry(); const x = bundle(); r.register(x); const altered = { ...x, provenanceId: "attacker" }; assert.throws(() => r.register(altered), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INTEGRITY_FAILURE"); });
test("F4-031 provider broad result cannot bypass local narrow scope", async () => { const r = new PolicyRegistry(); const x = ready(r, bundle({ rules: [{ id: "narrow", effect: "ALLOW", capabilityId: "evidence.read", scopePrefix: "evidence/narrow", reason: "narrow" }] })); let calls = 0; const a: PolicyDecisionAdapter = { evaluate: async () => { calls += 1; return { outcome: "ALLOW", provider: "remote", providerVersion: "1", decisionId: "broad", ruleId: "remote", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }; } }; const d = await new PolicyGovernance(r, a, lim()).evaluate(req({ scope: "evidence/broad" }), x.policyId); assert.equal(d.effect, "DENY"); assert.equal(calls, 0); });
test("F4-032 missing policy is typed", async () => { await expectCode(() => new PolicyGovernance(new PolicyRegistry(), new LocalDeterministicPolicyAdapter(), lim()).evaluate(req(), "missing"), "POLICY_NOT_FOUND"); });
test("F4-033 ambiguous activation is typed", () => { const r = new PolicyRegistry(); r.register(bundle({ version: "1" })); r.register(bundle({ version: "2" })); r.activate("access", "1", t1); assert.throws(() => r.activate("access", "2", t1), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_AMBIGUOUS"); });
test("F4-034 incompatibility is attributable", async () => { const r = new PolicyRegistry(); const x = ready(r); const a: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "PROVIDER_INCOMPATIBLE", provider: "x", providerVersion: "0", reason: "unsupported", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, a, lim()).evaluate(req(), x.policyId); assert.equal(d.evidence.failureCode, "POLICY_PROVIDER_INCOMPATIBLE"); });
test("F4-035 invalid provider outcome is indeterminate", async () => { const r = new PolicyRegistry(); const x = ready(r); const a: PolicyDecisionAdapter = { evaluate: async () => ({ outcome: "INVALID_RESULT", provider: "x", providerVersion: "1", reason: "bad", policyId: x.policyId, policyVersion: x.version, policyDigest: x.digest }) }; const d = await new PolicyGovernance(r, a, lim()).evaluate(req(), x.policyId); assert.equal(d.effect, "INDETERMINATE"); assert.equal(d.evidence.failureCode, "POLICY_INVALID_RESULT"); });
test("F4-036 duplicate registration never replaces first version", () => { const r = new PolicyRegistry(); const x = bundle(); const y = bundle({ rules: [{ id: "other", effect: "ALLOW", reason: "other" }] }); r.register(x); assert.throws(() => r.register(y), (e: unknown) => e instanceof PolicyGovernanceError && e.code === "POLICY_INTEGRITY_FAILURE"); assert.equal(r.get("access", "1").digest, x.digest); });
test("F4-037 repeated activation is idempotent", () => { const r = new PolicyRegistry(); const x = bundle(); r.register(x); r.activate("access", "1", t1); r.activate("access", "1", t1); assert.equal(r.lifecycleLog().filter((x) => x.action === "ACTIVATE").length, 1); });
test("F4-038 historical decision remains bound after retirement", async () => { const r = new PolicyRegistry(); const x = ready(r); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()); const a = await g.evaluate(req({ at: t1 }), x.policyId); r.retire(x.policyId, x.version, t2); const b = await g.evaluate(req({ at: t1 }), x.policyId, x.version); assert.deepEqual(a, b); });
test("F4-039 decision copies cannot mutate stored ledger evidence", async () => { const r = new PolicyRegistry(); const x = ready(r); const ledger = new InMemoryPolicyDecisionLedger(); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim(), ledger); const d = await g.evaluate(req(), x.policyId); const copy = ledger.all()[0]!; copy.evidence.reason = "mutated"; assert.equal(ledger.all()[0]!.evidence.reason, d.evidence.reason); });
test("F4-040 federated outcome remains locally attributable", async () => { const r = new PolicyRegistry(); const x = ready(r); const g = new PolicyGovernance(r, new LocalDeterministicPolicyAdapter(), lim()); const d = await g.evaluateFederated(req(), x.policyId, { originDomain: "remote", peerId: "peer-1", requestedCapability: "evidence.read", negotiatedCapability: "evidence.read", remotePolicyAssertion: "ALLOW" }); assert.equal(d.effect, "ALLOW"); assert.equal(d.evidence.policyVersion, x.version); });

void (0 as unknown as ExternalPolicyResult);
