import test from "node:test";
import assert from "node:assert/strict";
import { DeterministicSystemicSimulation, SystemicSimulationError, normalizeSystemicSimulationLimits, type SimulationAgent, type SimulationOrder, type SimulationScenario, type SimulationStrategy } from "../src/index.js";

const L=normalizeSystemicSimulationLimits({maxAgents:3,maxStrategies:3,maxInstitutions:2,maxResourcesPerAgent:2,maxOrdersPerTick:3,maxEvents:30,maxTicks:3,maxPayloadBytes:5000,maxEvidenceRefs:2});
const scenario=(o:Partial<SimulationScenario>={}):SimulationScenario=>({simulationId:"sim",seed:"seed",environment:"test",initialState:{v:1},...o});
const s=(id:string,mode="base"):SimulationStrategy=>({strategyId:id,name:mode,parameters:{risk:.5,mode}});
const agent=(id:string,strategyId="s1"):SimulationAgent=>({agentId:id,kind:"agent",label:id,resources:{cash:100},strategyId,createdAt:"2026-01-01T00:00:00.000Z"});
const sim=()=>{const x=new DeterministicSystemicSimulation(scenario(),L);x.registerStrategy(s("s1"));x.registerStrategy(s("s2","alt"));return x};
const ex=(f:()=>unknown,c:string)=>{let e:unknown;try{f()}catch(x){e=x}assert.equal(e instanceof SystemicSimulationError?e.code:undefined,c)};
const cases:Array<[string,()=>void]>=[];const add=(id:string,f:()=>void)=>cases.push([id,f]);
add("F7-001",()=>{const x=new DeterministicSystemicSimulation(scenario(),L);assert.equal(x.snapshot().simulationId,"sim")});
add("F7-002",()=>{const x=sim();assert.equal(x.registerStrategy(s("s3")).strategyId,"s3")});
add("F7-003",()=>{const x=sim(),a=x.createAgent(agent("a1"));assert.equal(a.agentId,"a1")});
add("F7-004",()=>{const x=sim(),a=x.createAgent(agent("a1"));a.label="x";assert.equal(x.snapshot().agents[0]!.label,"a1")});
add("F7-005",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.createAgent(agent("a1")),"STATE_CONFLICT")});
add("F7-006",()=>{const x=sim();for(const id of ["a1","a2","a3"])x.createAgent(agent(id));ex(()=>x.createAgent(agent("a4")),"RESOURCE_EXHAUSTED")});
add("F7-007",()=>{const x=sim();ex(()=>x.createAgent(agent("a1","missing")),"INVALID_INPUT")});
add("F7-008",()=>{const x=sim();ex(()=>x.createAgent({...agent("a1"),resources:{a:1,b:2,c:3}}),"RESOURCE_EXHAUSTED")});
add("F7-009",()=>{const x=sim();ex(()=>x.createAgent({...agent("a1"),resources:{cash:-1}}),"STATE_CONFLICT")});
add("F7-010",()=>{const x=sim();x.createAgent(agent("a1"));assert.equal(x.eventsAll().some(e=>e.type==="AGENT_CREATED"),true)});
add("F7-011",()=>{const x=sim();x.createAgent(agent("a1"));const y=x.snapshot();y.agents[0]!.resources.cash=0;assert.equal(x.snapshot().agents[0]!.resources.cash,100)});
add("F7-012",()=>{const x=sim();x.createAgent(agent("a1"));assert.equal(x.snapshot().agents.length,1)});
add("F7-013",()=>{const x=sim(),z=x.registerStrategy(s("s2","alt"));assert.equal(z.name,"alt")});
add("F7-014",()=>{const x=sim();x.createAgent(agent("a1"));const t=x.changeStrategy("a1","s2","reason");assert.equal(t.fromStrategyId,"s1")});
add("F7-015",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.changeStrategy("a1","s1","same"),"STATE_CONFLICT")});
add("F7-016",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.changeStrategy("none","s2","x"),"INVALID_INPUT")});
add("F7-017",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.changeStrategy("a1","none","x"),"INVALID_INPUT")});
add("F7-018",()=>{const x=sim();x.createAgent(agent("a1"));const a=x.changeStrategy("a1","s2","x"),b=x.eventsAll().at(-1)!;assert.equal(b.type,"STRATEGY_CHANGED");assert.equal(a.tick,0)});
add("F7-019",()=>{const x=sim();x.createAgent(agent("a1"));x.advanceTick();const t=x.changeStrategy("a1","s2","late");assert.equal(t.tick,1)});
add("F7-020",()=>{const x=sim();assert.equal(x.registerStrategy(s("s1")).strategyId,"s1")});
add("F7-021",()=>{const x=sim();x.createAgent(agent("a1"));const a=x.snapshot();x.changeStrategy("a1","s2","x");assert.equal(a.agents[0]!.strategyId,"s1")});
add("F7-022",()=>{const x=sim();x.createAgent(agent("a1"));assert.equal(x.eventsAll().filter(e=>e.type==="STRATEGY_CHANGED").length,0)});
add("F7-023",()=>{const x=sim();const z=x.registerStrategy(s("s3","z"));assert.equal(z.parameters.mode,"z")});
add("F7-024",()=>{const x=sim();const a=x.registerStrategy(s("s3"));const b=x.registerStrategy(s("s3"));assert.deepEqual(a,b)});
add("F7-025",()=>{const x=sim();const i=x.registerInstitution({institutionId:"i1",label:"Inst",scope:"local",roleIds:["r2","r1"],policyRefs:["p2","p1"]});assert.deepEqual(i.roleIds,["r1","r2"])});
add("F7-026",()=>{const x=sim();const i=x.registerInstitution({institutionId:"i1",label:"Inst",scope:"local",roleIds:[],policyRefs:[]});assert.deepEqual(i.policyRefs,[])});
add("F7-027",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"Inst",scope:"local",roleIds:[],policyRefs:[]});ex(()=>x.registerInstitution({institutionId:"i1",label:"Again",scope:"local",roleIds:[],policyRefs:[]}),"STATE_CONFLICT")});
add("F7-028",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"Inst",scope:"local",roleIds:[],policyRefs:[]});const z=x.snapshot();z.institutions[0]!.label="x";assert.equal(x.snapshot().institutions[0]!.label,"Inst")});
add("F7-029",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"1",scope:"s",roleIds:[],policyRefs:[]});x.registerInstitution({institutionId:"i2",label:"2",scope:"s",roleIds:[],policyRefs:[]});ex(()=>x.registerInstitution({institutionId:"i3",label:"3",scope:"s",roleIds:[],policyRefs:[]}),"RESOURCE_EXHAUSTED")});
add("F7-030",()=>{const x=sim();ex(()=>x.registerInstitution({institutionId:"",label:"x",scope:"s",roleIds:[],policyRefs:[]}),"INVALID_INPUT")});
add("F7-031",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"1",scope:"s",roleIds:[],policyRefs:["policy:v1"]});assert.equal(x.snapshot().institutions[0]!.policyRefs[0],"policy:v1")});
add("F7-032",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"1",scope:"s",roleIds:[],policyRefs:[]});assert.equal(x.eventsAll().some(e=>e.type==="INSTITUTION_REGISTERED"),true)});
add("F7-033",()=>{const x=sim();x.registerInstitution({institutionId:"i1",label:"1",scope:"s",roleIds:["r","r"],policyRefs:["p","p"]});assert.equal(x.snapshot().institutions[0]!.roleIds.length,1)});
add("F7-034",()=>{const x=sim();assert.throws(()=>x.assertNoAuthorityWidening(),SystemicSimulationError)});
add("F7-035",()=>{const x=sim();x.createAgent(agent("a1"));x.moveResource("a1","cash",-10);assert.equal(x.snapshot().agents[0]!.resources.cash,90)});
add("F7-036",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.moveResource("a1","cash",-101),"STATE_CONFLICT")});
add("F7-037",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.moveResource("a1","new",0),"INVALID_INPUT")});
add("F7-038",()=>{const x=sim();x.createAgent(agent("a1"));x.moveResource("a1","new",5);assert.equal(x.snapshot().agents[0]!.resources.new,5)});
add("F7-039",()=>{const x=sim();x.createAgent(agent("a1"));x.createAgent(agent("a2"));const a:SimulationOrder={orderId:"b1",agentId:"a1",side:"BUY",resource:"x",quantity:2,limitPrice:10,submittedTick:0};const b:SimulationOrder={orderId:"s1",agentId:"a2",side:"SELL",resource:"x",quantity:1,limitPrice:8,submittedTick:0};x.submitOrder(a);x.submitOrder(b);assert.equal(x.clearMarket("x").length,1)});
add("F7-040",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.submitOrder({orderId:"b",agentId:"no",side:"BUY",resource:"x",quantity:1,limitPrice:1,submittedTick:0}),"INVALID_INPUT")});
add("F7-041",()=>{const x=sim();x.createAgent(agent("a1"));x.createAgent(agent("a2"));x.submitOrder({orderId:"b",agentId:"a1",side:"BUY",resource:"x",quantity:1,limitPrice:10,submittedTick:0});x.submitOrder({orderId:"s",agentId:"a2",side:"SELL",resource:"x",quantity:1,limitPrice:10,submittedTick:0});const t=x.clearMarket("x")[0]!;assert.equal(t.price,10)});
add("F7-042",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.submitOrder({orderId:"b",agentId:"a1",side:"BUY",resource:"x",quantity:1,limitPrice:0,submittedTick:0}),"INVALID_INPUT")});
add("F7-043",()=>{const x=sim();x.createAgent(agent("a1"));ex(()=>x.submitOrder({orderId:"b",agentId:"a1",side:"BUY",resource:"x",quantity:0,limitPrice:1,submittedTick:0}),"INVALID_INPUT")});
add("F7-044",()=>{const x=sim();x.createAgent(agent("a1"));x.createAgent(agent("a2"));x.submitOrder({orderId:"b",agentId:"a1",side:"BUY",resource:"x",quantity:1,limitPrice:10,submittedTick:0});x.submitOrder({orderId:"s",agentId:"a2",side:"SELL",resource:"x",quantity:1,limitPrice:11,submittedTick:0});assert.equal(x.clearMarket("x").length,0)});
add("F7-045",()=>{const x=sim();assert.equal(x.tick,0);x.advanceTick();assert.equal(x.tick,1)});
add("F7-046",()=>{const x=sim();x.advanceTick();x.advanceTick();x.advanceTick();ex(()=>x.advanceTick(),"RESOURCE_EXHAUSTED")});
add("F7-047",()=>{const x=sim();x.createAgent(agent("a1"));x.scenarioInput({shock:1});assert.equal(x.eventsAll().at(-1)!.type,"SCENARIO_INPUT")});
add("F7-048",()=>{const x=sim();x.advanceTick();const e=x.eventsAll();assert.equal(e.every((v,i)=>v.sequence===i+1),true)});
add("F7-049",()=>{const x=sim();x.advanceTick();const s=x.snapshot();assert.equal(s.tick,1)});
add("F7-050",()=>{const x=sim();const a=x.snapshot().snapshotDigest,b=x.snapshot().snapshotDigest;assert.equal(a,b)});
add("F7-051",()=>{const x=sim();x.createAgent(agent("a1"));x.advanceTick();x.moveResource("a1","cash",-5);assert.doesNotThrow(()=>x.replay())});
add("F7-052",()=>{const x=sim();x.createAgent(agent("a1"));x.advanceTick();x.moveResource("a1","cash",-5);const r=x.replay(),s=x.snapshot();assert.equal(r.snapshotDigest,s.snapshotDigest)});
add("F7-053",()=>{const x=sim();x.createAgent(agent("a1"));const d=x.snapshot().snapshotDigest;x.createAgent(agent("a2"));assert.notEqual(x.snapshot().snapshotDigest,d)});
add("F7-054",()=>{const x=new DeterministicSystemicSimulation(scenario({seed:"a"}),L);const y=new DeterministicSystemicSimulation(scenario({seed:"a"}),L);x.registerStrategy(s("s1"));y.registerStrategy(s("s1"));x.createAgent(agent("a1"));y.createAgent(agent("a1"));assert.equal(x.snapshot().snapshotDigest,y.snapshot().snapshotDigest)});
add("F7-055",()=>{const x=sim();x.createAgent(agent("a1"));x.scenarioInput({remoteEvidence:{source:"federation"}});assert.equal(x.evidence().length,0)});
add("F7-056",()=>{const x=new DeterministicSystemicSimulation(scenario({evidenceRefs:[{evidenceId:"e",source:"KNOWLEDGE",digest:"d"}]}),L);assert.equal(x.evidence()[0]!.source,"KNOWLEDGE")});
add("F7-057",()=>{const x=new DeterministicSystemicSimulation(scenario({evidenceRefs:[{evidenceId:"e1",source:"KNOWLEDGE",digest:"d1"},{evidenceId:"e2",source:"POLICY",digest:"d2"}]}),L);assert.equal(x.evidence().length,2)});
add("F7-058",()=>{ex(()=>new DeterministicSystemicSimulation(scenario({evidenceRefs:[{evidenceId:"1",source:"SCENARIO",digest:"1"},{evidenceId:"2",source:"SCENARIO",digest:"2"},{evidenceId:"3",source:"SCENARIO",digest:"3"}]}),L),"RESOURCE_EXHAUSTED")});
add("F7-059",()=>{const x=sim();assert.equal(x.snapshot().trades.length,0);assert.equal(x.snapshot().openOrders.length,0)});
add("F7-060",()=>{const x=sim();x.createAgent(agent("a1"));x.createAgent(agent("a2"));x.registerInstitution({institutionId:"i1",label:"I",scope:"s",roleIds:[],policyRefs:["p1"]});x.submitOrder({orderId:"b",agentId:"a1",side:"BUY",resource:"x",quantity:1,limitPrice:10,submittedTick:0});x.submitOrder({orderId:"s",agentId:"a2",side:"SELL",resource:"x",quantity:1,limitPrice:9,submittedTick:0});x.clearMarket("x");x.advanceTick();assert.equal(x.replay().snapshotDigest,x.snapshot().snapshotDigest)});
assert.equal(cases.length,60);for(const [id,fn] of cases)test(id,fn);
