import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryEventStore, SifEventWriter } from "../src/core.js";
import { HashChainEventStore, AttestationSigner, AttestationVerifier } from "../src/integrity.js";
import { FileCas } from "../src/cas.js";
import { AuthorityRegistry } from "../src/core.js";
import { PolicyEngine } from "../src/policy.js";
import { InMemoryOutbox, OutboxDispatcher, PersistentJsonlOutbox } from "../src/outbox.js";
import { rmSync, mkdirSync, readFileSync } from "node:fs";
import { generateKeyPairSync } from "node:crypto";
import { join } from "node:path";

function temp(name: string): string { const p = join("/tmp", `sif-${name}-${Date.now()}-${Math.random().toString(36).slice(2)}`); mkdirSync(p, { recursive: true }); return p; }

test("hash-chain store verifies the chain and rejects tampered persisted events", async () => {
  const dir = temp("chain"), file = join(dir, "events.jsonl"); const { PersistentJsonlEventStore } = await import("../src/persistence.js"); const base = new PersistentJsonlEventStore(file); const chained = new HashChainEventStore(base); const writer = new SifEventWriter(chained);
  writer.write({ streamId: "s", eventType: "A", actorId: "a", correlationId: "c", payload: { n: 1 } }); writer.write({ streamId: "s", eventType: "B", actorId: "a", correlationId: "c", payload: { n: 2 } }); assert.equal(chained.verifyStream("s"), true);
  const raw = readFileSync(file, "utf8"); const tampered = raw.replace('"n":2', '"n":999'); const { writeFileSync, rmSync: rm } = await import("node:fs"); writeFileSync(file, tampered, "utf8"); assert.throws(() => new HashChainEventStore(new PersistentJsonlEventStore(file)), /digest mismatch/); rm(dir, { recursive: true, force: true });
});

test("file CAS stores by digest and detects corruption", () => { const root = temp("cas"); const cas = new FileCas(root); const d = cas.putJson({ b: 2, a: 1 }); assert.equal(cas.has(d), true); assert.deepEqual(cas.getJson(d), { b: 2, a: 1 }); assert.equal(readFileSync(join(root, d.slice(0, 2), d.slice(2))).length > 0, true); rmSync(root, { recursive: true, force: true }); });

test("ed25519 attestations sign and verify independently", () => { const { privateKey, publicKey } = generateKeyPairSync("ed25519"); const privatePem = privateKey.export({ type: "pkcs8", format: "pem" }).toString(); const publicPem = publicKey.export({ type: "spki", format: "pem" }).toString(); const signer = new AttestationSigner("issuer", privatePem); const attestation = signer.issue({ subjectDigest: "abc", subjectType: "artifact", payload: { x: 1 } }); const verifier = new AttestationVerifier(); assert.equal(verifier.verify(attestation, publicPem), true); assert.equal(verifier.verify({ ...attestation, subjectDigest: "tampered" }, publicPem), false); });

test("policy engine is default-deny and can use scoped authority", () => { const authority = new AuthorityRegistry(); authority.grant({ grantId: "g", subjectId: "agent", scope: "workspace", capabilities: ["read"], issuedAt: "2026-01-01T00:00:00.000Z", issuerId: "root" }); const policy = new PolicyEngine(authority); assert.equal(policy.decide({ subjectId: "agent", capabilityId: "read", scope: "workspace/a", at: "2026-03-01T00:00:00.000Z" }).effect, "allow"); assert.equal(policy.decide({ subjectId: "agent", capabilityId: "write", scope: "workspace/a", at: "2026-03-01T00:00:00.000Z" }).effect, "deny"); policy.addRule({ id: "deny-sensitive", effect: "deny", capability: "read", scopePrefix: "workspace/secret", reason: "Sensitive workspace is denied" }); assert.equal(policy.decide({ subjectId: "agent", capabilityId: "read", scope: "workspace/secret/x", at: "2026-03-01T00:00:00.000Z" }).ruleId, "deny-sensitive"); });

test("outbox is idempotent and retries failed delivery", () => { const outbox = new InMemoryOutbox(); const event = { eventId: "e1", eventType: "X", streamId: "s", streamVersion: 1, occurredAt: "2026-01-01T00:00:00.000Z", observedAt: "2026-01-01T00:00:00.000Z", actorId: "a", correlationId: "c", payload: { ok: true } }; const first = outbox.enqueue(event, "remote"); const second = outbox.enqueue(event, "remote"); assert.equal(first.outboxId, second.outboxId); let calls = 0; const dispatcher = new OutboxDispatcher(outbox, { send: () => { calls += 1; if (calls === 1) throw new Error("temporary"); } }); assert.equal(dispatcher.dispatchOnce(), 0); assert.equal(outbox.pending().length, 1); assert.equal(dispatcher.dispatchOnce(), 1); assert.equal(outbox.pending().length, 0); assert.equal(calls, 2); });

test("persistent outbox survives reload and keeps delivery idempotent", () => { const dir = temp("outbox"), file = join(dir, "outbox.jsonl"); const event = { eventId: "e2", eventType: "X", streamId: "s", streamVersion: 1, occurredAt: "2026-01-01T00:00:00.000Z", observedAt: "2026-01-01T00:00:00.000Z", actorId: "a", correlationId: "c", payload: { ok: true } }; const first = new PersistentJsonlOutbox(file); const item = first.enqueue(event, "remote"); first.markAttempt(item.outboxId); const second = new PersistentJsonlOutbox(file); assert.equal(second.pending().length, 1); assert.equal(second.pending()[0]?.attempts, 1); second.markDelivered(item.outboxId); const third = new PersistentJsonlOutbox(file); assert.equal(third.pending().length, 0); rmSync(dir, { recursive: true, force: true }); });

test("end-to-end flow records an event, protects integrity, gates policy and produces a durable delivery item", async () => { const dir = temp("e2e"); const { PersistentJsonlEventStore } = await import("../src/persistence.js"); const base = new PersistentJsonlEventStore(join(dir, "events.jsonl")); const store = new HashChainEventStore(base); const writer = new SifEventWriter(store); const event = writer.write({ streamId: "task:1", eventType: "TaskCreated", actorId: "agent", correlationId: "c1", payload: { task: "build" } }); assert.equal(store.verifyStream("task:1"), true); const authority = new AuthorityRegistry(); authority.grant({ grantId: "g", subjectId: "agent", scope: "tasks", capabilities: ["publish"], issuedAt: "2026-01-01T00:00:00.000Z", expiresAt: "2026-12-31T00:00:00.000Z", issuerId: "root" }); const policy = new PolicyEngine(authority); policy.enforce({ subjectId: "agent", capabilityId: "publish", scope: "tasks/1", at: "2026-03-01T00:00:00.000Z" }); const outbox = new PersistentJsonlOutbox(join(dir, "outbox.jsonl")); const item = outbox.enqueue(event, "federation:B"); assert.equal(outbox.pending()[0]?.payloadDigest.length, 64); assert.equal(item.eventId, event.eventId); rmSync(dir, { recursive: true, force: true }); });
